# Generated by Django 5.0.7 on 2024-07-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 TO 1000', '100 TO 1000'), ('1000 TO 10000', '1000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 30000', '20000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('50000 TO 100000', '50000 TO 100000'), ('100000 TO 1000000', '100000 TO 1000000')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='product_images')),
                ('image2', models.ImageField(upload_to='product_images')),
                ('image3', models.ImageField(upload_to='product_images')),
                ('image4', models.ImageField(upload_to='product_images')),
                ('color', models.CharField(max_length=50)),
                ('condtion', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=100)),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=30)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.filter_price')),
            ],
        ),
    ]
