# Generated by Django 5.0.7 on 2024-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='review_desp',
            field=models.TextField(),
        ),
    ]
