# Generated by Django 5.0.7 on 2024-07-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(choices=[(0, 'IN_STOCK'), (1, 'OUT_OF_STOCK')], default=1),
        ),
    ]
