# Generated by Django 5.0.7 on 2024-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('100 TO 200', '100 TO 200'), ('200 TO 500', '200 TO 500'), ('500 TO 1000', '500 TO 1000'), ('1000 TO 2000', '1000 TO 2000'), ('2000 TO 50000', '2000 TO 5000')], max_length=60),
        ),
    ]
