# Generated by Django 5.0.7 on 2024-07-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_filter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='review_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
