# Generated by Django 5.0.7 on 2024-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avg_rate',
            field=models.IntegerField(default=0),
        ),
    ]
