# Generated by Django 5.0.7 on 2024-07-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_products_avg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='avg_rate',
        ),
    ]
