# Generated by Django 5.0.7 on 2024-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(null=True, upload_to='profilepic')),
                ('joindate', models.DateField(auto_now_add=True, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
