# Generated by Django 5.0.7 on 2024-07-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
