# Generated by Django 5.0.7 on 2024-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headerimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headerimage')),
            ],
        ),
    ]
