# Generated by Django 5.0.7 on 2024-07-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_headerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headerimage',
        ),
    ]
