# Generated by Django 5.0.7 on 2024-07-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderitem',
        ),
        migrations.DeleteModel(
            name='Returns',
        ),
    ]
