# Generated by Django 5.0.7 on 2024-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
