# Generated by Django 5.0.7 on 2024-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_checkout_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='paymentid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
