# Generated by Django 5.0.7 on 2024-07-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='paid',
        ),
    ]
