# Generated by Django 5.0.7 on 2024-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_checkout_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='paymentid',
            new_name='orderid',
        ),
    ]
