# Generated by Django 5.0.7 on 2024-07-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_rename_paymentid_checkout_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderplaced',
        ),
    ]
