# Generated by Django 5.0.7 on 2024-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_delete_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'DELIVERED'), (3, 'SUCCESSED'), (4, 'REJECTED')], default=0),
        ),
    ]
