# Generated by Django 5.0.7 on 2024-07-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_cancelorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='date',
            new_name='order_date',
        ),
    ]
