# Generated by Django 5.0.7 on 2024-07-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_rename_date_checkout_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
