# Generated by Django 5.0.7 on 2024-07-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_checkout_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delivery_date',
        ),
    ]
