# Generated by Django 5.0.7 on 2024-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_checkout_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paymentid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
