# Generated by Django 5.0.7 on 2024-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_rename_create_at_order_order_date_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'ORDER_CONFIRMED'), (2, 'ORDER_DELIVERED'), (3, 'ORDER_REJECTED')], default=0),
        ),
    ]
