# Generated by Django 5.0.7 on 2024-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash on delivery', max_length=100),
        ),
    ]
