# Generated by Django 5.0.7 on 2024-07-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_headerimage'),
        ('order', '0032_alter_checkout_paymentmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='reson',
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='request_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customuser'),
        ),
    ]
