# Generated by Django 5.0.7 on 2024-07-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chekout', to='order.checkout'),
        ),
    ]
