# Generated by Django 5.0.7 on 2024-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.IntegerField(choices=[(1, 'ORDER_CONFIRMED'), (2, 'ORDER_SHIPPED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
